# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "talos-systems/talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.9.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.disaster-recovery]
        title = "Disaster Recovery"
        description = """\
* support for creating etcd snapshots (backups) with `talosctl etcd snapshot` command.
* etcd cluster can be recovered from a snapshot using `talosctl boostrap --recover-from=` command.
"""

    [notes.timesync]
        title = "Time Syncrhonization"
        description = """\
* `timed` service was replaced with a time sync controller, no machine configuration changes.
* Talos now prefers last successful time server (by IP address) on each sync attempt (improves sync accuracy).
"""

    [notes.sbcs]
        title = "SBCs"
        description = """\
* u-boot version was updated to fix the boot and USB issues on Raspberry Pi 4 8GiB version.
* added support for Rock Pi 4.
"""

    [notes.optimize]
        title = "Optmizations"
        description = """\
* Talos `system` services now run without container images on initramfs from the single executable; this change reduces RAM usage, initramfs size and boot time..
"""

    [notes.machineconfig-1]
        title = "Install Disk Selector"
        description = """\
Install section of the machine config now has `diskSelector` field that allows querying install disk using the list of qualifiers:

```yaml
...
  install:
    diskSelector:
      size: >= 500GB
      model: WDC*
...
```

`talosctl disks -n <node> -i` can be used to check allowed disk qualifiers when the node is running in the maintenance mode.
"""

    [notes.machineconfig-2]
        title = "Inline Kubernetes Manifests"
        description = """\
* boostrap manifests can now be submitted in the configuration body using the `cluster.inlineManifests` field.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/talos-systems/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/talos-systems/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/talos-systems/extras"
